---

- import_tasks: pre-checks.yml

- import_tasks: get-version.yml
  when: restic_version is not defined or not restic_version

- import_tasks: download-restic.yml

- import_tasks: install-restic.yml

- import_tasks: post-checks.yml
