---

- name: Check where bash is installed
  ansible.builtin.command: which bash
  register: restic_check_bash_path
  failed_when: restic_check_bash_path.rc > 0
  changed_when: false
  check_mode: false

- name: Check where crontab is installed
  ansible.builtin.command: which crontab
  register: restic_check_crontab_path
  failed_when: restic_check_crontab_path.rc > 0
  changed_when: false
  check_mode: false
  when: restic_scheduler == "cron"

- name: Check where bunzip2 is installed
  ansible.builtin.command: which bunzip2
  register: restic_check_bunzip2_path
  failed_when: restic_check_bunzip2_path.rc > 0
  changed_when: false
  check_mode: false

- name: Check for existing Restic binary
  ansible.builtin.stat:
    path: "{{ restic_install_dir }}/restic"
  register: restic_check_existing

- name: Check Restic binary version if binary already exists
  ansible.builtin.shell: |
    set -o pipefail
    {{ restic_install_dir }}/restic version 2>&1 | awk '{ print $2 }'
  args:
    executable: "{{ restic_check_bash_path.stdout_lines[0] }}"
  changed_when: false
  check_mode: false
  register: restic_check_existing_version
  when: restic_check_existing.stat.exists

- name: Ensure Restic existing version is set as a fact
  ansible.builtin.set_fact:
    restic_version_existing: "{{ restic_check_existing_version.stdout }}"
  when: restic_check_existing.stat.exists

- name: Check Restic role configuration
  ansible.builtin.assert:
    that:
      - restic_state in ['present', 'absent']
      - restic_scheduler in ['cron', 'systemd']
      - restic_repository is defined
      - restic_repository is string
      - restic_repository_password is defined
      - restic_repository_password is string
      - restic_repository_password | string | length > 8
      - restic_systemd_context is defined
      - restic_systemd_context in ['user', 'system']

- name: Ensure restic_repository_is_remote is set if repository is remote
  ansible.builtin.set_fact:
    restic_repository_is_remote: true
  when:
    - restic_repository is search(':')
    - restic_repository.split(':')[0] | lower in restic_remote_protocols
