---

- name: Check where bash is installed
  ansible.builtin.command: which bash
  register: restic_check_bash_path
  failed_when: restic_check_bash_path.rc > 0
  changed_when: false

- name: Check where bunzip2 is installed
  ansible.builtin.command: which bunzip2
  register: restic_check_bunzip2_path
  failed_when: restic_check_bunzip2_path.rc > 0
  changed_when: false

- name: Check for existing Restic binary
  ansible.builtin.stat:
    path: "{{ restic_install_dir }}/restic"
  register: restic_check_existing

- name: Check Restic binary version if binary already exists
  ansible.builtin.shell: |
    set -o pipefail
    {{ restic_install_dir }}/restic version 2>&1 | awk '{ print $2 }'
  args:
    executable: "{{ restic_check_bash_path.stdout_lines[0] }}"
  changed_when: false
  register: restic_check_existing_version
  when: restic_check_existing.stat.exists
