---

- name: Prepare
  hosts: all
  tasks:
    - name: Ensure bzip2 is installed
      ansible.builtin.package:
        name: bzip2
        state: present
      become: true

    - name: Ensure cron is installed
      ansible.builtin.package:
        name: cronie
        state: present
      become: true
