---

- name: Converge
  hosts: all
  become: true
  become_user: restic
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        restic_state: present
        restic_repository: "{{ ansible_user_dir }}/backup"
        restic_repository_password: S0m3th?nGB4d
        restic_files:
          - "{{ ansible_user_dir }}"
        restic_exclude_files:
          - "{{ ansible_user_dir }}/backup"
          - "{{ restic_config_dir }}"
